//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.9.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using AW.Dal.HelperClasses;
using AW.Dal.FactoryClasses;
using AW.Dal.RelationClasses;
using System.ComponentModel.DataAnnotations;
using SD.LLBLGen.Pro.ORMSupportClasses;

namespace AW.Dal.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END
	/// <summary>Entity class which represents the entity 'ContactType'.<br/><br/>MS_Description: Lookup table containing the types of contacts stored in Contact.<br/></summary>
	[Serializable]
	public partial class ContactTypeEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END	
	{
		private EntityCollection<VendorContactEntity> _vendorContacts;
		private EntityCollection<StoreContactEntity> _storeContacts;

		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END
		private static Dictionary<string, string>	_customProperties;
		private static Dictionary<string, Dictionary<string, string>>	_fieldsCustomProperties;
		private static ContactTypeEntityStaticMetaData _staticMetaData = new ContactTypeEntityStaticMetaData();
		private static ContactTypeRelations _relationsFactory = new ContactTypeRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
			/// <summary>Member name VendorContacts</summary>
			public static readonly string VendorContacts = "VendorContacts";
			/// <summary>Member name StoreContacts</summary>
			public static readonly string StoreContacts = "StoreContacts";
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class ContactTypeEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public ContactTypeEntityStaticMetaData()
			{
				SetEntityCoreInfo("ContactTypeEntity", InheritanceHierarchyType.None, false, (int)AW.Dal.EntityType.ContactTypeEntity, typeof(ContactTypeEntity), typeof(ContactTypeEntityFactory), false);
				AddNavigatorMetaData<ContactTypeEntity, EntityCollection<VendorContactEntity>>("VendorContacts", a => a._vendorContacts, (a, b) => a._vendorContacts = b, a => a.VendorContacts, () => new ContactTypeRelations().VendorContactEntityUsingContactTypeID, typeof(VendorContactEntity), (int)AW.Dal.EntityType.VendorContactEntity);
				AddNavigatorMetaData<ContactTypeEntity, EntityCollection<StoreContactEntity>>("StoreContacts", a => a._storeContacts, (a, b) => a._storeContacts = b, a => a.StoreContacts, () => new ContactTypeRelations().StoreContactEntityUsingContactTypeID, typeof(StoreContactEntity), (int)AW.Dal.EntityType.StoreContactEntity);
			}
		}

		/// <summary>Static ctor</summary>
		static ContactTypeEntity()
		{
			SetupCustomPropertyHashtables();
		}

		/// <summary> CTor</summary>
		public ContactTypeEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public ContactTypeEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this ContactTypeEntity</param>
		public ContactTypeEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="contactTypeID">PK value for ContactType which data should be fetched into this ContactType object</param>
		public ContactTypeEntity(AW.Data.ContactType contactTypeID) : this(contactTypeID, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="contactTypeID">PK value for ContactType which data should be fetched into this ContactType object</param>
		/// <param name="validator">The custom validator object for this ContactTypeEntity</param>
		public ContactTypeEntity(AW.Data.ContactType contactTypeID, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.ContactTypeID = contactTypeID;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected ContactTypeEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'VendorContact' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoVendorContacts() { return CreateRelationInfoForNavigator("VendorContacts"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'StoreContact' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoStoreContacts() { return CreateRelationInfoForNavigator("StoreContacts"); }
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END
			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the hashtables for the entity type and entity field custom properties. </summary>
		private static void SetupCustomPropertyHashtables()
		{
			_customProperties = new Dictionary<string, string>();
			_customProperties.Add("MS_Description", @"Lookup table containing the types of contacts stored in Contact.");
			_fieldsCustomProperties = new Dictionary<string, Dictionary<string, string>>();
			Dictionary<string, string> fieldHashtable;
			fieldHashtable = new Dictionary<string, string>();
			fieldHashtable.Add("MS_Description", @"Clustered index created by a primary key constraint.");
			_fieldsCustomProperties.Add("ContactTypeID", fieldHashtable);
			fieldHashtable = new Dictionary<string, string>();
			fieldHashtable.Add("MS_Description", @"Date and time the record was last updated.");
			_fieldsCustomProperties.Add("ModifiedDate", fieldHashtable);
			fieldHashtable = new Dictionary<string, string>();
			fieldHashtable.Add("MS_Description", @"Contact type description.");
			_fieldsCustomProperties.Add("Name", fieldHashtable);
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this ContactTypeEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static ContactTypeRelations Relations { get { return _relationsFactory; } }

		/// <summary>The custom properties for this entity type.</summary>
		/// <remarks>The data returned from this property should be considered read-only: it is not thread safe to alter this data at runtime.</remarks>
		public  static Dictionary<string, string> CustomProperties { get { return _customProperties;} }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'VendorContact' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathVendorContacts { get { return _staticMetaData.GetPrefetchPathElement("VendorContacts", CommonEntityBase.CreateEntityCollection<VendorContactEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'StoreContact' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathStoreContacts { get { return _staticMetaData.GetPrefetchPathElement("StoreContacts", CommonEntityBase.CreateEntityCollection<StoreContactEntity>()); } }

		/// <inheritdoc/>
		[Browsable(false), XmlIgnore]
		protected override Dictionary<string, string> CustomPropertiesOfType { get { return CustomProperties;} }

		/// <summary>The custom properties for the fields of this entity type. The returned Hashtable contains per fieldname a hashtable of name-value pairs. </summary>
		/// <remarks>The data returned from this property should be considered read-only: it is not thread safe to alter this data at runtime.</remarks>
		public  static Dictionary<string, Dictionary<string, string>> FieldsCustomProperties { get { return _fieldsCustomProperties;} }

		/// <inheritdoc/>
		[Browsable(false), XmlIgnore]
		protected override Dictionary<string, Dictionary<string, string>> FieldsCustomPropertiesOfType { get { return FieldsCustomProperties;} }

		/// <summary>The ContactTypeID property of the Entity ContactType<br/><br/>MS_Description: Clustered index created by a primary key constraint.<br/>Clustered index created by a primary key constraint.</summary>
		/// <remarks>Mapped on  table field: "ContactType"."ContactTypeID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, false</remarks>
		public virtual AW.Data.ContactType ContactTypeID
		{
			get { return (AW.Data.ContactType)GetValue((int)ContactTypeFieldIndex.ContactTypeID, true); }
			set { SetValue((int)ContactTypeFieldIndex.ContactTypeID, value); }		}

		/// <summary>The ModifiedDate property of the Entity ContactType<br/><br/>MS_Description: Date and time the record was last updated.<br/>Date and time the record was last updated.</summary>
		/// <remarks>Mapped on  table field: "ContactType"."ModifiedDate".<br/>Table field type characteristics (type, precision, scale, length): DateTime, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.DateTime ModifiedDate
		{
			get { return (System.DateTime)GetValue((int)ContactTypeFieldIndex.ModifiedDate, true); }
			set	{ SetValue((int)ContactTypeFieldIndex.ModifiedDate, value); }
		}

		/// <summary>The Name property of the Entity ContactType<br/><br/>MS_Description: Contact type description.<br/>Contact type description.</summary>
		/// <remarks>Mapped on  table field: "ContactType"."Name".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 50.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String Name
		{
			get { return (System.String)GetValue((int)ContactTypeFieldIndex.Name, true); }
			set	{ SetValue((int)ContactTypeFieldIndex.Name, value); }
		}

		/// <summary>Gets the EntityCollection with the related entities of type 'VendorContactEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/></summary>
		[TypeContainedAttribute(typeof(VendorContactEntity))]
		public virtual EntityCollection<VendorContactEntity> VendorContacts { get { return GetOrCreateEntityCollection<VendorContactEntity, VendorContactEntityFactory>("ContactType", true, false, ref _vendorContacts); } }

		/// <summary>Gets the EntityCollection with the related entities of type 'StoreContactEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/></summary>
		[TypeContainedAttribute(typeof(StoreContactEntity))]
		public virtual EntityCollection<StoreContactEntity> StoreContacts { get { return GetOrCreateEntityCollection<StoreContactEntity, StoreContactEntityFactory>("ContactType", true, false, ref _storeContacts); } }

		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END

	}
}

namespace AW.Dal
{
	public enum ContactTypeFieldIndex
	{
		///<summary>ContactTypeID. </summary>
		ContactTypeID,
		///<summary>ModifiedDate. </summary>
		ModifiedDate,
		///<summary>Name. </summary>
		Name,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace AW.Dal.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: ContactType. </summary>
	public partial class ContactTypeRelations: RelationFactory
	{
		/// <summary>Returns a new IEntityRelation object, between ContactTypeEntity and VendorContactEntity over the 1:n relation they have, using the relation between the fields: ContactType.ContactTypeID - VendorContact.ContactTypeID</summary>
		public virtual IEntityRelation VendorContactEntityUsingContactTypeID
		{
			get { return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "VendorContacts", true, new[] { ContactTypeFields.ContactTypeID, VendorContactFields.ContactTypeID }); }
		}

		/// <summary>Returns a new IEntityRelation object, between ContactTypeEntity and StoreContactEntity over the 1:n relation they have, using the relation between the fields: ContactType.ContactTypeID - StoreContact.ContactTypeID</summary>
		public virtual IEntityRelation StoreContactEntityUsingContactTypeID
		{
			get { return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "StoreContacts", true, new[] { ContactTypeFields.ContactTypeID, StoreContactFields.ContactTypeID }); }
		}

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticContactTypeRelations
	{
		internal static readonly IEntityRelation VendorContactEntityUsingContactTypeIDStatic = new ContactTypeRelations().VendorContactEntityUsingContactTypeID;
		internal static readonly IEntityRelation StoreContactEntityUsingContactTypeIDStatic = new ContactTypeRelations().StoreContactEntityUsingContactTypeID;

		/// <summary>CTor</summary>
		static StaticContactTypeRelations() { }
	}
}
