//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.9.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using AW.Dal.HelperClasses;
using AW.Dal.FactoryClasses;
using AW.Dal.RelationClasses;
using System.ComponentModel.DataAnnotations;
using SD.LLBLGen.Pro.ORMSupportClasses;

namespace AW.Dal.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END
	/// <summary>Entity class which represents the entity 'ProductModelIllustration'.<br/><br/>MS_Description: Cross-reference table mapping product models and illustrations.<br/></summary>
	[Serializable]
	public partial class ProductModelIllustrationEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END	
	{
		private IllustrationEntity _illustration;
		private ProductModelEntity _productModel;

		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END
		private static Dictionary<string, string>	_customProperties;
		private static Dictionary<string, Dictionary<string, string>>	_fieldsCustomProperties;
		private static ProductModelIllustrationEntityStaticMetaData _staticMetaData = new ProductModelIllustrationEntityStaticMetaData();
		private static ProductModelIllustrationRelations _relationsFactory = new ProductModelIllustrationRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
			/// <summary>Member name Illustration</summary>
			public static readonly string Illustration = "Illustration";
			/// <summary>Member name ProductModel</summary>
			public static readonly string ProductModel = "ProductModel";
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class ProductModelIllustrationEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public ProductModelIllustrationEntityStaticMetaData()
			{
				SetEntityCoreInfo("ProductModelIllustrationEntity", InheritanceHierarchyType.None, false, (int)AW.Dal.EntityType.ProductModelIllustrationEntity, typeof(ProductModelIllustrationEntity), typeof(ProductModelIllustrationEntityFactory), false);
				AddNavigatorMetaData<ProductModelIllustrationEntity, IllustrationEntity>("Illustration", "ProductModelIllustrations", (a, b) => a._illustration = b, a => a._illustration, (a, b) => a.Illustration = b, AW.Dal.RelationClasses.StaticProductModelIllustrationRelations.IllustrationEntityUsingIllustrationIDStatic, ()=>new ProductModelIllustrationRelations().IllustrationEntityUsingIllustrationID, null, new int[] { (int)ProductModelIllustrationFieldIndex.IllustrationID }, null, true, (int)AW.Dal.EntityType.IllustrationEntity);
				AddNavigatorMetaData<ProductModelIllustrationEntity, ProductModelEntity>("ProductModel", "ProductModelIllustrations", (a, b) => a._productModel = b, a => a._productModel, (a, b) => a.ProductModel = b, AW.Dal.RelationClasses.StaticProductModelIllustrationRelations.ProductModelEntityUsingProductModelIDStatic, ()=>new ProductModelIllustrationRelations().ProductModelEntityUsingProductModelID, null, new int[] { (int)ProductModelIllustrationFieldIndex.ProductModelID }, null, true, (int)AW.Dal.EntityType.ProductModelEntity);
			}
		}

		/// <summary>Static ctor</summary>
		static ProductModelIllustrationEntity()
		{
			SetupCustomPropertyHashtables();
		}

		/// <summary> CTor</summary>
		public ProductModelIllustrationEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public ProductModelIllustrationEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this ProductModelIllustrationEntity</param>
		public ProductModelIllustrationEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="illustrationID">PK value for ProductModelIllustration which data should be fetched into this ProductModelIllustration object</param>
		/// <param name="productModelID">PK value for ProductModelIllustration which data should be fetched into this ProductModelIllustration object</param>
		public ProductModelIllustrationEntity(System.Int32 illustrationID, System.Int32 productModelID) : this(illustrationID, productModelID, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="illustrationID">PK value for ProductModelIllustration which data should be fetched into this ProductModelIllustration object</param>
		/// <param name="productModelID">PK value for ProductModelIllustration which data should be fetched into this ProductModelIllustration object</param>
		/// <param name="validator">The custom validator object for this ProductModelIllustrationEntity</param>
		public ProductModelIllustrationEntity(System.Int32 illustrationID, System.Int32 productModelID, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.IllustrationID = illustrationID;
			this.ProductModelID = productModelID;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected ProductModelIllustrationEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'Illustration' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoIllustration() { return CreateRelationInfoForNavigator("Illustration"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'ProductModel' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoProductModel() { return CreateRelationInfoForNavigator("ProductModel"); }
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END
			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the hashtables for the entity type and entity field custom properties. </summary>
		private static void SetupCustomPropertyHashtables()
		{
			_customProperties = new Dictionary<string, string>();
			_customProperties.Add("MS_Description", @"Cross-reference table mapping product models and illustrations.");
			_fieldsCustomProperties = new Dictionary<string, Dictionary<string, string>>();
			Dictionary<string, string> fieldHashtable;
			fieldHashtable = new Dictionary<string, string>();
			fieldHashtable.Add("MS_Description", @"Primary key. Foreign key to Illustration.IllustrationID.");
			_fieldsCustomProperties.Add("IllustrationID", fieldHashtable);
			fieldHashtable = new Dictionary<string, string>();
			fieldHashtable.Add("MS_Description", @"Date and time the record was last updated.");
			_fieldsCustomProperties.Add("ModifiedDate", fieldHashtable);
			fieldHashtable = new Dictionary<string, string>();
			fieldHashtable.Add("MS_Description", @"Clustered index created by a primary key constraint.");
			_fieldsCustomProperties.Add("ProductModelID", fieldHashtable);
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this ProductModelIllustrationEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static ProductModelIllustrationRelations Relations { get { return _relationsFactory; } }

		/// <summary>The custom properties for this entity type.</summary>
		/// <remarks>The data returned from this property should be considered read-only: it is not thread safe to alter this data at runtime.</remarks>
		public  static Dictionary<string, string> CustomProperties { get { return _customProperties;} }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'Illustration' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathIllustration { get { return _staticMetaData.GetPrefetchPathElement("Illustration", CommonEntityBase.CreateEntityCollection<IllustrationEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'ProductModel' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathProductModel { get { return _staticMetaData.GetPrefetchPathElement("ProductModel", CommonEntityBase.CreateEntityCollection<ProductModelEntity>()); } }

		/// <inheritdoc/>
		[Browsable(false), XmlIgnore]
		protected override Dictionary<string, string> CustomPropertiesOfType { get { return CustomProperties;} }

		/// <summary>The custom properties for the fields of this entity type. The returned Hashtable contains per fieldname a hashtable of name-value pairs. </summary>
		/// <remarks>The data returned from this property should be considered read-only: it is not thread safe to alter this data at runtime.</remarks>
		public  static Dictionary<string, Dictionary<string, string>> FieldsCustomProperties { get { return _fieldsCustomProperties;} }

		/// <inheritdoc/>
		[Browsable(false), XmlIgnore]
		protected override Dictionary<string, Dictionary<string, string>> FieldsCustomPropertiesOfType { get { return FieldsCustomProperties;} }

		/// <summary>The IllustrationID property of the Entity ProductModelIllustration<br/><br/>MS_Description: Primary key. Foreign key to Illustration.IllustrationID.<br/>Primary key. Foreign key to Illustration.IllustrationID.</summary>
		/// <remarks>Mapped on  table field: "ProductModelIllustration"."IllustrationID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, false</remarks>
		public virtual System.Int32 IllustrationID
		{
			get { return (System.Int32)GetValue((int)ProductModelIllustrationFieldIndex.IllustrationID, true); }
			set	{ SetValue((int)ProductModelIllustrationFieldIndex.IllustrationID, value); }
		}

		/// <summary>The ModifiedDate property of the Entity ProductModelIllustration<br/><br/>MS_Description: Date and time the record was last updated.<br/>Date and time the record was last updated.</summary>
		/// <remarks>Mapped on  table field: "ProductModelIllustration"."ModifiedDate".<br/>Table field type characteristics (type, precision, scale, length): DateTime, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.DateTime ModifiedDate
		{
			get { return (System.DateTime)GetValue((int)ProductModelIllustrationFieldIndex.ModifiedDate, true); }
			set	{ SetValue((int)ProductModelIllustrationFieldIndex.ModifiedDate, value); }
		}

		/// <summary>The ProductModelID property of the Entity ProductModelIllustration<br/><br/>MS_Description: Clustered index created by a primary key constraint.<br/>Clustered index created by a primary key constraint.</summary>
		/// <remarks>Mapped on  table field: "ProductModelIllustration"."ProductModelID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, false</remarks>
		public virtual System.Int32 ProductModelID
		{
			get { return (System.Int32)GetValue((int)ProductModelIllustrationFieldIndex.ProductModelID, true); }
			set	{ SetValue((int)ProductModelIllustrationFieldIndex.ProductModelID, value); }
		}

		/// <summary>Gets / sets related entity of type 'IllustrationEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(false)]
		public virtual IllustrationEntity Illustration
		{
			get { return _illustration; }
			set { SetSingleRelatedEntityNavigator(value, "Illustration"); }
		}

		/// <summary>Gets / sets related entity of type 'ProductModelEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(false)]
		public virtual ProductModelEntity ProductModel
		{
			get { return _productModel; }
			set { SetSingleRelatedEntityNavigator(value, "ProductModel"); }
		}

		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END

	}
}

namespace AW.Dal
{
	public enum ProductModelIllustrationFieldIndex
	{
		///<summary>IllustrationID. </summary>
		IllustrationID,
		///<summary>ModifiedDate. </summary>
		ModifiedDate,
		///<summary>ProductModelID. </summary>
		ProductModelID,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace AW.Dal.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: ProductModelIllustration. </summary>
	public partial class ProductModelIllustrationRelations: RelationFactory
	{

		/// <summary>Returns a new IEntityRelation object, between ProductModelIllustrationEntity and IllustrationEntity over the m:1 relation they have, using the relation between the fields: ProductModelIllustration.IllustrationID - Illustration.IllustrationID</summary>
		public virtual IEntityRelation IllustrationEntityUsingIllustrationID
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "Illustration", false, new[] { IllustrationFields.IllustrationID, ProductModelIllustrationFields.IllustrationID }); }
		}

		/// <summary>Returns a new IEntityRelation object, between ProductModelIllustrationEntity and ProductModelEntity over the m:1 relation they have, using the relation between the fields: ProductModelIllustration.ProductModelID - ProductModel.ProductModelID</summary>
		public virtual IEntityRelation ProductModelEntityUsingProductModelID
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "ProductModel", false, new[] { ProductModelFields.ProductModelID, ProductModelIllustrationFields.ProductModelID }); }
		}

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticProductModelIllustrationRelations
	{
		internal static readonly IEntityRelation IllustrationEntityUsingIllustrationIDStatic = new ProductModelIllustrationRelations().IllustrationEntityUsingIllustrationID;
		internal static readonly IEntityRelation ProductModelEntityUsingProductModelIDStatic = new ProductModelIllustrationRelations().ProductModelEntityUsingProductModelID;

		/// <summary>CTor</summary>
		static StaticProductModelIllustrationRelations() { }
	}
}
