//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.9.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using AW.Dal.HelperClasses;
using AW.Dal.FactoryClasses;
using AW.Dal.RelationClasses;
using System.ComponentModel.DataAnnotations;
using SD.LLBLGen.Pro.ORMSupportClasses;

namespace AW.Dal.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END
	/// <summary>Entity class which represents the entity 'SalesOrderDetail'.<br/><br/>MS_Description: Individual products associated with a specific sales order. See SalesOrderHeader.<br/></summary>
	[Serializable]
	public partial class SalesOrderDetailEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END	
	{
		private SalesOrderHeaderEntity _salesOrderHeader;
		private SpecialOfferProductEntity _specialOfferProduct;
		private SalesOrderHistoryEntity _salesOrderHistory;

		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END
		private static Dictionary<string, string>	_customProperties;
		private static Dictionary<string, Dictionary<string, string>>	_fieldsCustomProperties;
		private static SalesOrderDetailEntityStaticMetaData _staticMetaData = new SalesOrderDetailEntityStaticMetaData();
		private static SalesOrderDetailRelations _relationsFactory = new SalesOrderDetailRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
			/// <summary>Member name SalesOrderHeader</summary>
			public static readonly string SalesOrderHeader = "SalesOrderHeader";
			/// <summary>Member name SpecialOfferProduct</summary>
			public static readonly string SpecialOfferProduct = "SpecialOfferProduct";
			/// <summary>Member name SalesOrderHistory</summary>
			public static readonly string SalesOrderHistory = "SalesOrderHistory";
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class SalesOrderDetailEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public SalesOrderDetailEntityStaticMetaData()
			{
				SetEntityCoreInfo("SalesOrderDetailEntity", InheritanceHierarchyType.None, false, (int)AW.Dal.EntityType.SalesOrderDetailEntity, typeof(SalesOrderDetailEntity), typeof(SalesOrderDetailEntityFactory), false);
				AddNavigatorMetaData<SalesOrderDetailEntity, SalesOrderHeaderEntity>("SalesOrderHeader", "SalesOrderDetails", (a, b) => a._salesOrderHeader = b, a => a._salesOrderHeader, (a, b) => a.SalesOrderHeader = b, AW.Dal.RelationClasses.StaticSalesOrderDetailRelations.SalesOrderHeaderEntityUsingSalesOrderIDStatic, ()=>new SalesOrderDetailRelations().SalesOrderHeaderEntityUsingSalesOrderID, null, new int[] { (int)SalesOrderDetailFieldIndex.SalesOrderID }, null, true, (int)AW.Dal.EntityType.SalesOrderHeaderEntity);
				AddNavigatorMetaData<SalesOrderDetailEntity, SpecialOfferProductEntity>("SpecialOfferProduct", "SalesOrderDetails", (a, b) => a._specialOfferProduct = b, a => a._specialOfferProduct, (a, b) => a.SpecialOfferProduct = b, AW.Dal.RelationClasses.StaticSalesOrderDetailRelations.SpecialOfferProductEntityUsingProductIDSpecialOfferIDStatic, ()=>new SalesOrderDetailRelations().SpecialOfferProductEntityUsingProductIDSpecialOfferID, null, new int[] { (int)SalesOrderDetailFieldIndex.ProductID, (int)SalesOrderDetailFieldIndex.SpecialOfferID }, null, true, (int)AW.Dal.EntityType.SpecialOfferProductEntity);
				AddNavigatorMetaData<SalesOrderDetailEntity, SalesOrderHistoryEntity>("SalesOrderHistory", "SalesOrderDetail", (a, b) => a._salesOrderHistory = b, a => a._salesOrderHistory, (a, b) => a.SalesOrderHistory = b, AW.Dal.RelationClasses.StaticSalesOrderDetailRelations.SalesOrderHistoryEntityUsingReferenceOrderLineIDReferenceOrderIDStatic, ()=>new SalesOrderDetailRelations().SalesOrderHistoryEntityUsingReferenceOrderLineIDReferenceOrderID, null, null, null, true, (int)AW.Dal.EntityType.SalesOrderHistoryEntity);
			}
		}

		/// <summary>Static ctor</summary>
		static SalesOrderDetailEntity()
		{
			SetupCustomPropertyHashtables();
		}

		/// <summary> CTor</summary>
		public SalesOrderDetailEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public SalesOrderDetailEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this SalesOrderDetailEntity</param>
		public SalesOrderDetailEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="salesOrderDetailID">PK value for SalesOrderDetail which data should be fetched into this SalesOrderDetail object</param>
		/// <param name="salesOrderID">PK value for SalesOrderDetail which data should be fetched into this SalesOrderDetail object</param>
		public SalesOrderDetailEntity(System.Int32 salesOrderDetailID, System.Int32 salesOrderID) : this(salesOrderDetailID, salesOrderID, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="salesOrderDetailID">PK value for SalesOrderDetail which data should be fetched into this SalesOrderDetail object</param>
		/// <param name="salesOrderID">PK value for SalesOrderDetail which data should be fetched into this SalesOrderDetail object</param>
		/// <param name="validator">The custom validator object for this SalesOrderDetailEntity</param>
		public SalesOrderDetailEntity(System.Int32 salesOrderDetailID, System.Int32 salesOrderID, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.SalesOrderDetailID = salesOrderDetailID;
			this.SalesOrderID = salesOrderID;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected SalesOrderDetailEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'SalesOrderHeader' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoSalesOrderHeader() { return CreateRelationInfoForNavigator("SalesOrderHeader"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'SpecialOfferProduct' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoSpecialOfferProduct() { return CreateRelationInfoForNavigator("SpecialOfferProduct"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'SalesOrderHistory' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoSalesOrderHistory() { return CreateRelationInfoForNavigator("SalesOrderHistory"); }
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END
			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the hashtables for the entity type and entity field custom properties. </summary>
		private static void SetupCustomPropertyHashtables()
		{
			_customProperties = new Dictionary<string, string>();
			_customProperties.Add("MS_Description", @"Individual products associated with a specific sales order. See SalesOrderHeader.");
			_fieldsCustomProperties = new Dictionary<string, Dictionary<string, string>>();
			Dictionary<string, string> fieldHashtable;
			fieldHashtable = new Dictionary<string, string>();
			fieldHashtable.Add("MS_Description", @"Nonclustered index.");
			_fieldsCustomProperties.Add("CarrierTrackingNumber", fieldHashtable);
			fieldHashtable = new Dictionary<string, string>();
			fieldHashtable.Add("MS_Description", @"Per product subtotal. Computed as UnitPrice * (1 - UnitPriceDiscount) * OrderQty.");
			_fieldsCustomProperties.Add("LineTotal", fieldHashtable);
			fieldHashtable = new Dictionary<string, string>();
			fieldHashtable.Add("MS_Description", @"Date and time the record was last updated.");
			_fieldsCustomProperties.Add("ModifiedDate", fieldHashtable);
			fieldHashtable = new Dictionary<string, string>();
			fieldHashtable.Add("MS_Description", @"Quantity ordered per product.");
			_fieldsCustomProperties.Add("OrderQty", fieldHashtable);
			fieldHashtable = new Dictionary<string, string>();
			fieldHashtable.Add("MS_Description", @"Product sold to customer. Foreign key to Product.ProductID.");
			_fieldsCustomProperties.Add("ProductID", fieldHashtable);
			fieldHashtable = new Dictionary<string, string>();
			fieldHashtable.Add("MS_Description", @"ROWGUIDCOL number uniquely identifying the record. Used to support a merge replication sample.");
			_fieldsCustomProperties.Add("Rowguid", fieldHashtable);
			fieldHashtable = new Dictionary<string, string>();
			fieldHashtable.Add("MS_Description", @"Primary key. One incremental unique number per product sold.");
			_fieldsCustomProperties.Add("SalesOrderDetailID", fieldHashtable);
			fieldHashtable = new Dictionary<string, string>();
			fieldHashtable.Add("MS_Description", @"Clustered index created by a primary key constraint.");
			_fieldsCustomProperties.Add("SalesOrderID", fieldHashtable);
			fieldHashtable = new Dictionary<string, string>();
			fieldHashtable.Add("MS_Description", @"Promotional code. Foreign key to SpecialOffer.SpecialOfferID.");
			_fieldsCustomProperties.Add("SpecialOfferID", fieldHashtable);
			fieldHashtable = new Dictionary<string, string>();
			fieldHashtable.Add("MS_Description", @"Selling price of a single product.");
			_fieldsCustomProperties.Add("UnitPrice", fieldHashtable);
			fieldHashtable = new Dictionary<string, string>();
			fieldHashtable.Add("MS_Description", @"Discount amount.");
			_fieldsCustomProperties.Add("UnitPriceDiscount", fieldHashtable);
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this SalesOrderDetailEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static SalesOrderDetailRelations Relations { get { return _relationsFactory; } }

		/// <summary>The custom properties for this entity type.</summary>
		/// <remarks>The data returned from this property should be considered read-only: it is not thread safe to alter this data at runtime.</remarks>
		public  static Dictionary<string, string> CustomProperties { get { return _customProperties;} }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'SalesOrderHeader' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathSalesOrderHeader { get { return _staticMetaData.GetPrefetchPathElement("SalesOrderHeader", CommonEntityBase.CreateEntityCollection<SalesOrderHeaderEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'SpecialOfferProduct' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathSpecialOfferProduct { get { return _staticMetaData.GetPrefetchPathElement("SpecialOfferProduct", CommonEntityBase.CreateEntityCollection<SpecialOfferProductEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'SalesOrderHistory' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathSalesOrderHistory { get { return _staticMetaData.GetPrefetchPathElement("SalesOrderHistory", CommonEntityBase.CreateEntityCollection<SalesOrderHistoryEntity>()); } }

		/// <inheritdoc/>
		[Browsable(false), XmlIgnore]
		protected override Dictionary<string, string> CustomPropertiesOfType { get { return CustomProperties;} }

		/// <summary>The custom properties for the fields of this entity type. The returned Hashtable contains per fieldname a hashtable of name-value pairs. </summary>
		/// <remarks>The data returned from this property should be considered read-only: it is not thread safe to alter this data at runtime.</remarks>
		public  static Dictionary<string, Dictionary<string, string>> FieldsCustomProperties { get { return _fieldsCustomProperties;} }

		/// <inheritdoc/>
		[Browsable(false), XmlIgnore]
		protected override Dictionary<string, Dictionary<string, string>> FieldsCustomPropertiesOfType { get { return FieldsCustomProperties;} }

		/// <summary>The CarrierTrackingNumber property of the Entity SalesOrderDetail<br/><br/>MS_Description: Nonclustered index.<br/>Nonclustered index.</summary>
		/// <remarks>Mapped on  table field: "SalesOrderDetail"."CarrierTrackingNumber".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 25.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String CarrierTrackingNumber
		{
			get { return (System.String)GetValue((int)SalesOrderDetailFieldIndex.CarrierTrackingNumber, true); }
			set	{ SetValue((int)SalesOrderDetailFieldIndex.CarrierTrackingNumber, value); }
		}

		/// <summary>The LineTotal property of the Entity SalesOrderDetail<br/><br/>MS_Description: Per product subtotal. Computed as UnitPrice * (1 - UnitPriceDiscount) * OrderQty.<br/>Per product subtotal. Computed as UnitPrice * (1 - UnitPriceDiscount) * OrderQty.</summary>
		/// <remarks>Mapped on  table field: "SalesOrderDetail"."LineTotal".<br/>Table field type characteristics (type, precision, scale, length): Decimal, 38, 6, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Decimal LineTotal
		{
			get { return (System.Decimal)GetValue((int)SalesOrderDetailFieldIndex.LineTotal, true); }
		}

		/// <summary>The ModifiedDate property of the Entity SalesOrderDetail<br/><br/>MS_Description: Date and time the record was last updated.<br/>Date and time the record was last updated.</summary>
		/// <remarks>Mapped on  table field: "SalesOrderDetail"."ModifiedDate".<br/>Table field type characteristics (type, precision, scale, length): DateTime, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.DateTime ModifiedDate
		{
			get { return (System.DateTime)GetValue((int)SalesOrderDetailFieldIndex.ModifiedDate, true); }
			set	{ SetValue((int)SalesOrderDetailFieldIndex.ModifiedDate, value); }
		}

		/// <summary>The OrderQty property of the Entity SalesOrderDetail<br/><br/>MS_Description: Quantity ordered per product.<br/>Quantity ordered per product.</summary>
		/// <remarks>Mapped on  table field: "SalesOrderDetail"."OrderQty".<br/>Table field type characteristics (type, precision, scale, length): SmallInt, 5, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Int16 OrderQty
		{
			get { return (System.Int16)GetValue((int)SalesOrderDetailFieldIndex.OrderQty, true); }
			set	{ SetValue((int)SalesOrderDetailFieldIndex.OrderQty, value); }
		}

		/// <summary>The ProductID property of the Entity SalesOrderDetail<br/><br/>MS_Description: Product sold to customer. Foreign key to Product.ProductID.<br/>Product sold to customer. Foreign key to Product.ProductID.</summary>
		/// <remarks>Mapped on  table field: "SalesOrderDetail"."ProductID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Int32 ProductID
		{
			get { return (System.Int32)GetValue((int)SalesOrderDetailFieldIndex.ProductID, true); }
			set	{ SetValue((int)SalesOrderDetailFieldIndex.ProductID, value); }
		}

		/// <summary>The Rowguid property of the Entity SalesOrderDetail<br/><br/>MS_Description: ROWGUIDCOL number uniquely identifying the record. Used to support a merge replication sample.<br/>ROWGUIDCOL number uniquely identifying the record. Used to support a merge replication sample.</summary>
		/// <remarks>Mapped on  table field: "SalesOrderDetail"."rowguid".<br/>Table field type characteristics (type, precision, scale, length): UniqueIdentifier, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Guid Rowguid
		{
			get { return (System.Guid)GetValue((int)SalesOrderDetailFieldIndex.Rowguid, true); }
			set	{ SetValue((int)SalesOrderDetailFieldIndex.Rowguid, value); }
		}

		/// <summary>The SalesOrderDetailID property of the Entity SalesOrderDetail<br/><br/>MS_Description: Primary key. One incremental unique number per product sold.<br/>Primary key. One incremental unique number per product sold.</summary>
		/// <remarks>Mapped on  table field: "SalesOrderDetail"."SalesOrderDetailID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, true</remarks>
		public virtual System.Int32 SalesOrderDetailID
		{
			get { return (System.Int32)GetValue((int)SalesOrderDetailFieldIndex.SalesOrderDetailID, true); }
			set { SetValue((int)SalesOrderDetailFieldIndex.SalesOrderDetailID, value); }		}

		/// <summary>The SalesOrderID property of the Entity SalesOrderDetail<br/><br/>MS_Description: Clustered index created by a primary key constraint.<br/>Clustered index created by a primary key constraint.</summary>
		/// <remarks>Mapped on  table field: "SalesOrderDetail"."SalesOrderID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, false</remarks>
		public virtual System.Int32 SalesOrderID
		{
			get { return (System.Int32)GetValue((int)SalesOrderDetailFieldIndex.SalesOrderID, true); }
			set	{ SetValue((int)SalesOrderDetailFieldIndex.SalesOrderID, value); }
		}

		/// <summary>The SpecialOfferID property of the Entity SalesOrderDetail<br/><br/>MS_Description: Promotional code. Foreign key to SpecialOffer.SpecialOfferID.<br/>Promotional code. Foreign key to SpecialOffer.SpecialOfferID.</summary>
		/// <remarks>Mapped on  table field: "SalesOrderDetail"."SpecialOfferID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Int32 SpecialOfferID
		{
			get { return (System.Int32)GetValue((int)SalesOrderDetailFieldIndex.SpecialOfferID, true); }
			set	{ SetValue((int)SalesOrderDetailFieldIndex.SpecialOfferID, value); }
		}

		/// <summary>The UnitPrice property of the Entity SalesOrderDetail<br/><br/>MS_Description: Selling price of a single product.<br/>Selling price of a single product.</summary>
		/// <remarks>Mapped on  table field: "SalesOrderDetail"."UnitPrice".<br/>Table field type characteristics (type, precision, scale, length): Money, 19, 4, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Decimal UnitPrice
		{
			get { return (System.Decimal)GetValue((int)SalesOrderDetailFieldIndex.UnitPrice, true); }
			set	{ SetValue((int)SalesOrderDetailFieldIndex.UnitPrice, value); }
		}

		/// <summary>The UnitPriceDiscount property of the Entity SalesOrderDetail<br/><br/>MS_Description: Discount amount.<br/>Discount amount.</summary>
		/// <remarks>Mapped on  table field: "SalesOrderDetail"."UnitPriceDiscount".<br/>Table field type characteristics (type, precision, scale, length): Money, 19, 4, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Decimal UnitPriceDiscount
		{
			get { return (System.Decimal)GetValue((int)SalesOrderDetailFieldIndex.UnitPriceDiscount, true); }
			set	{ SetValue((int)SalesOrderDetailFieldIndex.UnitPriceDiscount, value); }
		}

		/// <summary>Gets / sets related entity of type 'SalesOrderHeaderEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(false)]
		public virtual SalesOrderHeaderEntity SalesOrderHeader
		{
			get { return _salesOrderHeader; }
			set { SetSingleRelatedEntityNavigator(value, "SalesOrderHeader"); }
		}

		/// <summary>Gets / sets related entity of type 'SpecialOfferProductEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(false)]
		public virtual SpecialOfferProductEntity SpecialOfferProduct
		{
			get { return _specialOfferProduct; }
			set { SetSingleRelatedEntityNavigator(value, "SpecialOfferProduct"); }
		}

		/// <summary>Gets / sets related entity of type 'SalesOrderHistoryEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned.<br/><br/></summary>
		[Browsable(false)]
		public virtual SalesOrderHistoryEntity SalesOrderHistory
		{
			get { return _salesOrderHistory; }
			set { SetSingleRelatedEntityNavigator(value, "SalesOrderHistory"); }
		}

		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END

	}
}

namespace AW.Dal
{
	public enum SalesOrderDetailFieldIndex
	{
		///<summary>CarrierTrackingNumber. </summary>
		CarrierTrackingNumber,
		///<summary>LineTotal. </summary>
		LineTotal,
		///<summary>ModifiedDate. </summary>
		ModifiedDate,
		///<summary>OrderQty. </summary>
		OrderQty,
		///<summary>ProductID. </summary>
		ProductID,
		///<summary>Rowguid. </summary>
		Rowguid,
		///<summary>SalesOrderDetailID. </summary>
		SalesOrderDetailID,
		///<summary>SalesOrderID. </summary>
		SalesOrderID,
		///<summary>SpecialOfferID. </summary>
		SpecialOfferID,
		///<summary>UnitPrice. </summary>
		UnitPrice,
		///<summary>UnitPriceDiscount. </summary>
		UnitPriceDiscount,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace AW.Dal.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: SalesOrderDetail. </summary>
	public partial class SalesOrderDetailRelations: RelationFactory
	{

		/// <summary>Returns a new IEntityRelation object, between SalesOrderDetailEntity and SalesOrderHistoryEntity over the 1:1 relation they have, using the relation between the fields: SalesOrderDetail.SalesOrderDetailID - SalesOrderHistory.ReferenceOrderLineID, SalesOrderDetail.SalesOrderID - SalesOrderHistory.ReferenceOrderID</summary>
		public virtual IEntityRelation SalesOrderHistoryEntityUsingReferenceOrderLineIDReferenceOrderID
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToOne, "SalesOrderHistory", true, new[] { SalesOrderDetailFields.SalesOrderDetailID, SalesOrderHistoryFields.ReferenceOrderLineID, SalesOrderDetailFields.SalesOrderID, SalesOrderHistoryFields.ReferenceOrderID }); }
		}

		/// <summary>Returns a new IEntityRelation object, between SalesOrderDetailEntity and SalesOrderHeaderEntity over the m:1 relation they have, using the relation between the fields: SalesOrderDetail.SalesOrderID - SalesOrderHeader.SalesOrderID</summary>
		public virtual IEntityRelation SalesOrderHeaderEntityUsingSalesOrderID
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "SalesOrderHeader", false, new[] { SalesOrderHeaderFields.SalesOrderID, SalesOrderDetailFields.SalesOrderID }); }
		}

		/// <summary>Returns a new IEntityRelation object, between SalesOrderDetailEntity and SpecialOfferProductEntity over the m:1 relation they have, using the relation between the fields: SalesOrderDetail.ProductID - SpecialOfferProduct.ProductID, SalesOrderDetail.SpecialOfferID - SpecialOfferProduct.SpecialOfferID</summary>
		public virtual IEntityRelation SpecialOfferProductEntityUsingProductIDSpecialOfferID
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "SpecialOfferProduct", false, new[] { SpecialOfferProductFields.ProductID, SalesOrderDetailFields.ProductID, SpecialOfferProductFields.SpecialOfferID, SalesOrderDetailFields.SpecialOfferID }); }
		}

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticSalesOrderDetailRelations
	{
		internal static readonly IEntityRelation SalesOrderHistoryEntityUsingReferenceOrderLineIDReferenceOrderIDStatic = new SalesOrderDetailRelations().SalesOrderHistoryEntityUsingReferenceOrderLineIDReferenceOrderID;
		internal static readonly IEntityRelation SalesOrderHeaderEntityUsingSalesOrderIDStatic = new SalesOrderDetailRelations().SalesOrderHeaderEntityUsingSalesOrderID;
		internal static readonly IEntityRelation SpecialOfferProductEntityUsingProductIDSpecialOfferIDStatic = new SalesOrderDetailRelations().SpecialOfferProductEntityUsingProductIDSpecialOfferID;

		/// <summary>CTor</summary>
		static StaticSalesOrderDetailRelations() { }
	}
}
