//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.9.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using AW.Dal.HelperClasses;
using AW.Dal.FactoryClasses;
using AW.Dal.RelationClasses;
using System.ComponentModel.DataAnnotations;
using SD.LLBLGen.Pro.ORMSupportClasses;

namespace AW.Dal.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END
	/// <summary>Entity class which represents the entity 'VendorContact'.<br/><br/>MS_Description: Cross-reference table mapping vendors and their employees.<br/></summary>
	[Serializable]
	public partial class VendorContactEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END	
	{
		private ContactEntity _contact;
		private ContactTypeEntity _contactType;
		private VendorEntity _vendor;

		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END
		private static Dictionary<string, string>	_customProperties;
		private static Dictionary<string, Dictionary<string, string>>	_fieldsCustomProperties;
		private static VendorContactEntityStaticMetaData _staticMetaData = new VendorContactEntityStaticMetaData();
		private static VendorContactRelations _relationsFactory = new VendorContactRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
			/// <summary>Member name Contact</summary>
			public static readonly string Contact = "Contact";
			/// <summary>Member name ContactType</summary>
			public static readonly string ContactType = "ContactType";
			/// <summary>Member name Vendor</summary>
			public static readonly string Vendor = "Vendor";
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class VendorContactEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public VendorContactEntityStaticMetaData()
			{
				SetEntityCoreInfo("VendorContactEntity", InheritanceHierarchyType.None, false, (int)AW.Dal.EntityType.VendorContactEntity, typeof(VendorContactEntity), typeof(VendorContactEntityFactory), false);
				AddNavigatorMetaData<VendorContactEntity, ContactEntity>("Contact", "VendorContacts", (a, b) => a._contact = b, a => a._contact, (a, b) => a.Contact = b, AW.Dal.RelationClasses.StaticVendorContactRelations.ContactEntityUsingContactIDStatic, ()=>new VendorContactRelations().ContactEntityUsingContactID, null, new int[] { (int)VendorContactFieldIndex.ContactID }, null, true, (int)AW.Dal.EntityType.ContactEntity);
				AddNavigatorMetaData<VendorContactEntity, ContactTypeEntity>("ContactType", "VendorContacts", (a, b) => a._contactType = b, a => a._contactType, (a, b) => a.ContactType = b, AW.Dal.RelationClasses.StaticVendorContactRelations.ContactTypeEntityUsingContactTypeIDStatic, ()=>new VendorContactRelations().ContactTypeEntityUsingContactTypeID, null, new int[] { (int)VendorContactFieldIndex.ContactTypeID }, null, true, (int)AW.Dal.EntityType.ContactTypeEntity);
				AddNavigatorMetaData<VendorContactEntity, VendorEntity>("Vendor", "VendorContacts", (a, b) => a._vendor = b, a => a._vendor, (a, b) => a.Vendor = b, AW.Dal.RelationClasses.StaticVendorContactRelations.VendorEntityUsingVendorIDStatic, ()=>new VendorContactRelations().VendorEntityUsingVendorID, null, new int[] { (int)VendorContactFieldIndex.VendorID }, null, true, (int)AW.Dal.EntityType.VendorEntity);
			}
		}

		/// <summary>Static ctor</summary>
		static VendorContactEntity()
		{
			SetupCustomPropertyHashtables();
		}

		/// <summary> CTor</summary>
		public VendorContactEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public VendorContactEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this VendorContactEntity</param>
		public VendorContactEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="contactID">PK value for VendorContact which data should be fetched into this VendorContact object</param>
		/// <param name="vendorID">PK value for VendorContact which data should be fetched into this VendorContact object</param>
		public VendorContactEntity(System.Int32 contactID, System.Int32 vendorID) : this(contactID, vendorID, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="contactID">PK value for VendorContact which data should be fetched into this VendorContact object</param>
		/// <param name="vendorID">PK value for VendorContact which data should be fetched into this VendorContact object</param>
		/// <param name="validator">The custom validator object for this VendorContactEntity</param>
		public VendorContactEntity(System.Int32 contactID, System.Int32 vendorID, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.ContactID = contactID;
			this.VendorID = vendorID;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected VendorContactEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'Contact' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoContact() { return CreateRelationInfoForNavigator("Contact"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'ContactType' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoContactType() { return CreateRelationInfoForNavigator("ContactType"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'Vendor' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoVendor() { return CreateRelationInfoForNavigator("Vendor"); }
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END
			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the hashtables for the entity type and entity field custom properties. </summary>
		private static void SetupCustomPropertyHashtables()
		{
			_customProperties = new Dictionary<string, string>();
			_customProperties.Add("MS_Description", @"Cross-reference table mapping vendors and their employees.");
			_fieldsCustomProperties = new Dictionary<string, Dictionary<string, string>>();
			Dictionary<string, string> fieldHashtable;
			fieldHashtable = new Dictionary<string, string>();
			fieldHashtable.Add("MS_Description", @"Contact (Vendor employee) identification number. Foreign key to Contact.ContactID.");
			_fieldsCustomProperties.Add("ContactID", fieldHashtable);
			fieldHashtable = new Dictionary<string, string>();
			fieldHashtable.Add("MS_Description", @"Nonclustered index.");
			_fieldsCustomProperties.Add("ContactTypeID", fieldHashtable);
			fieldHashtable = new Dictionary<string, string>();
			fieldHashtable.Add("MS_Description", @"Date and time the record was last updated.");
			_fieldsCustomProperties.Add("ModifiedDate", fieldHashtable);
			fieldHashtable = new Dictionary<string, string>();
			fieldHashtable.Add("MS_Description", @"Clustered index created by a primary key constraint.");
			_fieldsCustomProperties.Add("VendorID", fieldHashtable);
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this VendorContactEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static VendorContactRelations Relations { get { return _relationsFactory; } }

		/// <summary>The custom properties for this entity type.</summary>
		/// <remarks>The data returned from this property should be considered read-only: it is not thread safe to alter this data at runtime.</remarks>
		public  static Dictionary<string, string> CustomProperties { get { return _customProperties;} }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'Contact' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathContact { get { return _staticMetaData.GetPrefetchPathElement("Contact", CommonEntityBase.CreateEntityCollection<ContactEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'ContactType' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathContactType { get { return _staticMetaData.GetPrefetchPathElement("ContactType", CommonEntityBase.CreateEntityCollection<ContactTypeEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'Vendor' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathVendor { get { return _staticMetaData.GetPrefetchPathElement("Vendor", CommonEntityBase.CreateEntityCollection<VendorEntity>()); } }

		/// <inheritdoc/>
		[Browsable(false), XmlIgnore]
		protected override Dictionary<string, string> CustomPropertiesOfType { get { return CustomProperties;} }

		/// <summary>The custom properties for the fields of this entity type. The returned Hashtable contains per fieldname a hashtable of name-value pairs. </summary>
		/// <remarks>The data returned from this property should be considered read-only: it is not thread safe to alter this data at runtime.</remarks>
		public  static Dictionary<string, Dictionary<string, string>> FieldsCustomProperties { get { return _fieldsCustomProperties;} }

		/// <inheritdoc/>
		[Browsable(false), XmlIgnore]
		protected override Dictionary<string, Dictionary<string, string>> FieldsCustomPropertiesOfType { get { return FieldsCustomProperties;} }

		/// <summary>The ContactID property of the Entity VendorContact<br/><br/>MS_Description: Contact (Vendor employee) identification number. Foreign key to Contact.ContactID.<br/>Contact (Vendor employee) identification number. Foreign key to Contact.ContactID.</summary>
		/// <remarks>Mapped on  table field: "VendorContact"."ContactID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, false</remarks>
		public virtual System.Int32 ContactID
		{
			get { return (System.Int32)GetValue((int)VendorContactFieldIndex.ContactID, true); }
			set	{ SetValue((int)VendorContactFieldIndex.ContactID, value); }
		}

		/// <summary>The ContactTypeID property of the Entity VendorContact<br/><br/>MS_Description: Nonclustered index.<br/>Nonclustered index.</summary>
		/// <remarks>Mapped on  table field: "VendorContact"."ContactTypeID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual AW.Data.ContactType ContactTypeID
		{
			get { return (AW.Data.ContactType)GetValue((int)VendorContactFieldIndex.ContactTypeID, true); }
			set	{ SetValue((int)VendorContactFieldIndex.ContactTypeID, value); }
		}

		/// <summary>The ModifiedDate property of the Entity VendorContact<br/><br/>MS_Description: Date and time the record was last updated.<br/>Date and time the record was last updated.</summary>
		/// <remarks>Mapped on  table field: "VendorContact"."ModifiedDate".<br/>Table field type characteristics (type, precision, scale, length): DateTime, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.DateTime ModifiedDate
		{
			get { return (System.DateTime)GetValue((int)VendorContactFieldIndex.ModifiedDate, true); }
			set	{ SetValue((int)VendorContactFieldIndex.ModifiedDate, value); }
		}

		/// <summary>The VendorID property of the Entity VendorContact<br/><br/>MS_Description: Clustered index created by a primary key constraint.<br/>Clustered index created by a primary key constraint.</summary>
		/// <remarks>Mapped on  table field: "VendorContact"."VendorID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, false</remarks>
		public virtual System.Int32 VendorID
		{
			get { return (System.Int32)GetValue((int)VendorContactFieldIndex.VendorID, true); }
			set	{ SetValue((int)VendorContactFieldIndex.VendorID, value); }
		}

		/// <summary>Gets / sets related entity of type 'ContactEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(false)]
		public virtual ContactEntity Contact
		{
			get { return _contact; }
			set { SetSingleRelatedEntityNavigator(value, "Contact"); }
		}

		/// <summary>Gets / sets related entity of type 'ContactTypeEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(false)]
		public virtual ContactTypeEntity ContactType
		{
			get { return _contactType; }
			set { SetSingleRelatedEntityNavigator(value, "ContactType"); }
		}

		/// <summary>Gets / sets related entity of type 'VendorEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(false)]
		public virtual VendorEntity Vendor
		{
			get { return _vendor; }
			set { SetSingleRelatedEntityNavigator(value, "Vendor"); }
		}

		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END

	}
}

namespace AW.Dal
{
	public enum VendorContactFieldIndex
	{
		///<summary>ContactID. </summary>
		ContactID,
		///<summary>ContactTypeID. </summary>
		ContactTypeID,
		///<summary>ModifiedDate. </summary>
		ModifiedDate,
		///<summary>VendorID. </summary>
		VendorID,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace AW.Dal.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: VendorContact. </summary>
	public partial class VendorContactRelations: RelationFactory
	{

		/// <summary>Returns a new IEntityRelation object, between VendorContactEntity and ContactEntity over the m:1 relation they have, using the relation between the fields: VendorContact.ContactID - Contact.ContactID</summary>
		public virtual IEntityRelation ContactEntityUsingContactID
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "Contact", false, new[] { ContactFields.ContactID, VendorContactFields.ContactID }); }
		}

		/// <summary>Returns a new IEntityRelation object, between VendorContactEntity and ContactTypeEntity over the m:1 relation they have, using the relation between the fields: VendorContact.ContactTypeID - ContactType.ContactTypeID</summary>
		public virtual IEntityRelation ContactTypeEntityUsingContactTypeID
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "ContactType", false, new[] { ContactTypeFields.ContactTypeID, VendorContactFields.ContactTypeID }); }
		}

		/// <summary>Returns a new IEntityRelation object, between VendorContactEntity and VendorEntity over the m:1 relation they have, using the relation between the fields: VendorContact.VendorID - Vendor.VendorID</summary>
		public virtual IEntityRelation VendorEntityUsingVendorID
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "Vendor", false, new[] { VendorFields.VendorID, VendorContactFields.VendorID }); }
		}

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticVendorContactRelations
	{
		internal static readonly IEntityRelation ContactEntityUsingContactIDStatic = new VendorContactRelations().ContactEntityUsingContactID;
		internal static readonly IEntityRelation ContactTypeEntityUsingContactTypeIDStatic = new VendorContactRelations().ContactTypeEntityUsingContactTypeID;
		internal static readonly IEntityRelation VendorEntityUsingVendorIDStatic = new VendorContactRelations().VendorEntityUsingVendorID;

		/// <summary>CTor</summary>
		static StaticVendorContactRelations() { }
	}
}
